### ISSUE TITLE
Height dnote

### ISSUE THREAD

**Issue by Ved-un** [kolunmi/dnote#2]
Thanks for the project.
How do I increase the height of the notification?
I couldn't find such a setting in the config...

**Comment by kolunmi** [comment]
You're welcome! All notifications are mapped raised to max height. Could you be more specific?

**Comment by Ved-un** [comment]
As I understand the height of the notification window depends on the size of the font, but how to increase me margin?

![flameshot_288_1](https://user-images.githubusercontent.com/48730277/195968178-1b56a5fa-4166-4fa6-a8cb-e776a9b93fef.png)

**Comment by Ved-un** [comment]
Okay, I thought about it and it probably doesn't make sense, 
these notifications don't support multiple lines anyway, and with a single line, increasing the height of the frame doesn't make much sense.

I think we can close this issue.

**Comment by kolunmi** [comment]
They do support multiple lines. Try catting a multi-line file into dnote.

I added two new constants to config.h, text_padding and contents_padding_vertical. Do these address your issue?

**Comment by Ved-un** [comment]
Yay! Thank you very much!

![flameshot_288](https://user-images.githubusercontent.com/48730277/195978116-b5466b51-86a3-4983-87a6-d312409772e6.png)
