### ISSUE TITLE
Uncritical question

### ISSUE THREAD

**Issue by Ved-un** [kolunmi/dnote#3]
Hello.
As I understand it, there is only one way to restart the **dnote** `killall dnoted; dnoted &`

I enter these commands into the terminal

`echo "Test 1" | dnote -exp 0; sleep 3s; killall dnoted; dnoted &; echo "Test 2" | dnote -exp 2`

and "Test 2" doesn't work.
```
[elem] ~ ❯ echo "Test 1" | dnote -exp 10; sleep 3s; killall dnoted; dnoted &; echo "Test 2" | dnote -exp 2      (02:38)

[1] 38900
[2]  - 28430 terminated  dnoted
failed to connect to the socket
[elem] ~ ❯
```
But if I set a pause after restarting **dnote**  0,1 sec

`echo "Test 1" | dnote -exp 0; sleep 3; killall dnoted; dnoted &; sleep 0.1; echo "Test 2" | dnote -exp 2`

then everything works fine.

Why is it like this?

**Comment by kolunmi** [comment]
I believe when you spawn `dnoted &` (a new child process) there is a very brief period where the program is not hosting the socket as it performs setup. The shell rapidly proceeds to execute `echo "Test 2" | dnote -exp 2` before this window ends, and it fails to connect.

I'm not sure how I would rectify this issue. Perhaps the dnote client could nanosleep and make another attempt n times, but that might be improper.

Why do you want to restart dnoted? When you pass `-exp 0` to dnote, the notification is persistent until the user clicks on the window. Would you like a way to cancel the notification via the command line? Or something else?

**Comment by Ved-un** [comment]
> Why do you want to restart dnoted? When you pass `-exp 0` to dnote, the notification is persistent until the user clicks on the window. Would you like a way to cancel the notification via the command line?

I use the **cron** to periodically run the **rsynс** script to back up the files I need.

At the beginning of the backup, I trigger the **"Backup system"** notification so I don't accidentally shut down the computer at that time, and at the end of the backup the notification should reset and a new one should appear for a short time  **"Backup system OK!"**, meaning that the backup is over.

**Comment by Ved-un** [comment]
Here is an example of my **rsync.sh** script :

```
#!/bin/zsh

echo "Backup system" | dnote -exp 0

# backup /home/elem
rsync -acv --delete-excluded --exclude-from '/home/elem/.local/bin/rsync.sh.ex' /home/elem /mnt/Backup/Arch-Q

echo "Backup system OK!" | dnote -exp 2
```

**Comment by Ved-un** [comment]
I tried to change my script like this, but it does not work :

```
#!/bin/zsh

echo "Backup system" | dnote -exp 0

# backup /home/elem
rsync -acv --delete-excluded --exclude-from '/home/elem/.local/bin/rsync.sh.ex' /home/elem /mnt/Backup/Arch-Q

killall dnoted; dnoted &

sleep 0.1; echo "Backup system OK!" | dnote -exp 2
```
Although if you run this from the terminal, it works fine : 

`echo "Test 1" | dnote -exp 10; sleep 3s; killall dnoted; dnoted &; echo "Test 2" | dnote -exp 2`

**Comment by Ved-un** [comment]
Now I tried to run my script mmm from the terminal and everything works fine:

```
#!/bin/zsh

echo "Backup system" | dnote -exp 0

# backup /home/elem
rsync -acv --delete-excluded --exclude-from '/home/elem/.local/bin/rsync.sh.ex' /home/elem /mnt/Backup/Arch-Q

killall dnoted; dnoted &; sleep 0.1

echo "Backup system OK!" | dnote -exp 2
```

Apparently I have some problem running it from the **cron**.

Dear friend, thanks for the answers, I'll probably close this question.

**Comment by kolunmi** [comment]
A better way to do this is with the -id option, for example
`
#!/bin/zsh

DNOTEID='unique_string'

echo "Backup system" | dnote -id "$DNOTEID" -exp 0

# backup /home/elem
rsync -acv --delete-excluded --exclude-from '/home/elem/.local/bin/rsync.sh.ex' /home/elem /mnt/Backup/Arch-Q

echo "Backup system OK!" | dnote -id "$DNOTEID" -exp 2
`
This way, the initial notification will be overwritten with new settings when the operation is over, thus achieving your goal.

I think I will also add a way to cancel notifications forcibly via dnote, since that would be useful in some circumstances.

**Comment by Ved-un** [comment]
As I understand it - there's the whole problem with this **cron**.... - **dnoted** doesn't want to start from the cron, although everything runs fine from the user...

I guess I'll have to move away from the **cron** and try to use the **systemd** timer...

I apologize for my English, I'm writing with a translator

**Comment by Ved-un** [comment]
I'm new to this stuff, but I think the whole reason is that **cron** jobs are run from another user and **dnoted** can't create a socket from **cron**, so it won't start

**Comment by Ved-un** [comment]
I'm getting pretty fed up with this **cron**.
I also struggled with launching **dunst** from the **cron**,
But it was easier for me there - **dunst** communicates via **dbus**.

I don't want to go back to **dunst** for a few notifications, I respect good compact code and it's not because **dnote** consumes 8 mb and **dunst** almost 30 mb...

it's about the concept of

**Comment by Ved-un** [comment]
> A better way to do this is with the -id option, for example

Thanks for the advice... I'll try a little later, but I think that's not the point - the point is that the cron runs this script from another user and starting a new daemon **detoted** doesn't work when starting from it

**Comment by Ved-un** [comment]
Okay friend, it's all nonsense and it doesn't concern your project.

It's the little things, and I think I'll figure it out, and at the same time I'll get some knowledge ))

**Comment by Ved-un** [comment]
Your advice is welcome, though.

**Comment by Ved-un** [comment]
Apparently the way it works is that if a **dnoted** creates its own personal user socket - it cannot even after resetting and starting it create a new one - if it will be started e.g. via the **cron**

**Comment by Ved-un** [comment]
I'm dumb at this, but it must create its own socket somewhere, for example in the **tmp** folder... it's logical

But then why when I kill **dnote** - I can not restart it from the cron?

In the terminal from the user everything works fine and the script works, but ONLY under the user...

my script doesn't run under a user

**Comment by Ved-un** [comment]
How can I change the command in the cron to run it from a user?

**Comment by Ved-un** [comment]
The cron runs this script of mine and does everything right except one thing - no restart of notifications dnote...

there is a demon kill, but there is NO startup of a new daemon of denote (

**Comment by Ved-un** [comment]
I already say as a sorcerer - running daemon denoted - it can be killed, but its socket remains unkilled and so it does not allow to create a new socket from another user... -because it's not completely killed and it exists 

I'm telling you this as an esotericist

**Comment by Ved-un** [comment]
That is, the cron my script understands where it says `killall dnoted`
but here right away and does not understand `dnoted &`

**Comment by Ved-un** [comment]
I need a simple restart from the command line, but apparently it depends on who launched it - that it can run...

And the **cron** does not work from a user, as I understand it?

**Comment by Ved-un** [comment]
Should I try to link this cron parasha to the cron folder I created in my space and then these commands will work from me - from the user?

**Comment by Ved-un** [comment]
If the dnote is run from me - everything works fine in my script

But I do not need to run it manually? - it should automatically back me up - and the cron is probably a dumb thing that doesn't understand my scripts

my script kills dnoted from the cron, but then it won't run it

**Comment by Ved-un** [comment]
While I reopen
Can anyone else give me a hint?

Where's my mistake?

**Comment by Ved-un** [comment]
I'm a dumb person, but the idea is that when you start this daemon from the user - it creates its own socket, which I can kill and re-create just because I own it ... - I'm the king of it.

And if I create a command in the cron - a script where the commands dnot run the cron - they just tell me to fuck off as a system user?

**Comment by Ved-un** [comment]
it turns out that I can kill dnoted from my script, running from the cron, but I can't restart it

because when I run it from the cron it chooses a different socket, which does not exist in nature...

am i right?

**Comment by Ved-un** [comment]
But it's not the bottom - it's probably a problem with the crown... It's so dumb that I've had enough trouble even with the dunst scripts.

**Comment by kolunmi** [comment]
There are definitely permission issues occurring with the socket file in /tmp ... since What error message does dnoted or cron give when you attempt to restart it via cron?

**Comment by Ved-un** [comment]
That's it, I've figured out the launch from the **cron**.

The problem is that the **cron** does not read the set variables and it needs to specify them separately, I added the variables to the file **cron**:

```
DISPLAY=:0
XDG_RUNTIME_DIR=/tmp/runtime-root
DBUS_SESSION_BUS_ADDRESS=/tmp/runtime-root/bus
PATH=/home/elem/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin

00 00 * * * rsync.sh > /mnt/Backup/Arch-Q/rsync.log
00 12 * * * rsync.sh > /mnt/Backup/Arch-Q/rsync.log
00 15 * * * mirrors
```

and all the **dnote** commands in my scripts worked properly.

Hooray


https://user-images.githubusercontent.com/48730277/197390823-eff64876-7f2e-4113-aa6b-69f1c9f889e1.mp4

**Comment by Ved-un** [comment]
@kolunmi 
Once again, thank you so much for the project !

**Comment by Ved-un** [comment]
> A better way to do this is with the -id option, for example

Тhanks for the advice, absolutely right, why would the daemon dnoted restart? - I changed everything and created a script _timebar_
```
#!/bin/zsh
# command 'timebar [text] [stop time]'

for i in {0..$2}; do
	echo $1 $i sec | dnote -exp 0 -id abc
	sleep 1s
done
```
and then changed my _rsyinc.sh_ script

```
#!/bin/zsh

timebar "Rsync" 300 &

pkexec rsync -acv --delete /etc /mnt/Backup/Arch-Q

killall timebar
```
Everything is working great for me now!
Thanks

**Comment by Ved-un** [comment]
It's even better than what I had before

https://user-images.githubusercontent.com/48730277/198833660-c9d0207e-3932-493e-ad42-bd5ad2bdfd71.mp4

**Comment by Ved-un** [comment]
@kolunmi 
The only thing you can add is to kill a window by its ID

**Comment by Ved-un** [comment]
My script 

```
#!/bin/sh

for i in {60..0}; do
	echo Suspend after $i min | dnote -id abc -minw 180 -exp 3600 -pbar $i 60
	sleep 1m
done

echo Suspend after 0 min | dnote -id abc -minw 180 -exp 0.1 -pbar 0 60

sudo zzz
```

![flameshot_304](https://user-images.githubusercontent.com/48730277/198936119-1d2da3d7-af91-409d-a14f-16d0c913d308.png)

**Comment by kolunmi** [comment]
> The only thing you can add is to kill a window by its ID

Once I'm done implementing png support, I will definitely add that feature since it is pretty fundamental. Thanks for all the support and feedback!

**Comment by kolunmi** [comment]
@Ved-un I added a new binary to the project called dnotec (control), and you can kill a window using `dnotec -kill "$ID"`. There are some rough edges so let me know if you encounter any issues
