### ISSUE TITLE
Project name & fuse dnote with dnoted

### ISSUE THREAD

**Issue by wael444** [kolunmi/dnote#4]
Based on a reddit comment by user u/wael444, who probably maybe isn't me:

> imo I also think the name sounds pretty weird and doesn't fit the purpose of the project

You said you named this after dmenu and notification. But the d in dmenu so dynamic and I don't think this program is very dynamic since it comes with 3 programs together

I believe there should be: `dnote`, `dnotectl`/`dnotec`, `dnote -d`! And the default action of `dnote` is to launch as daemon

There's similar notification programs : `herbe`, `xnotify`, `dunst`

Maybe this project can be named something new that doesn't sound like a note taking program?

**Comment by Ved-un** [comment]
That's right, you should remove the **d** from the name and call it something like - **noti**

**Comment by wael444** [comment]
If suckless would name this project maybe it would be `sn`? 'simple notification' or `snotif`

Alternatively: `notif`

**Comment by kolunmi** [comment]
> Maybe this project can be named something new that doesn't sound like a note taking program?

You're right, it does kind of sound like a note taking application

> And the default action of dnote is to launch as daemon

'Fusing' dnote and dnoted would be pointless and require that redundant dnoted code be loaded into memory every time the client is invoked to spawn a new notification. It also would obfuscate the source imo.

> If suckless would name this project maybe it would be sn? 'simple notification' or snotif

I like these suggestions, but `sn` sounds too much like a coreutil and `snotif` sounds a little silly when pronounced.

> I don't think this program is very dynamic since it comes with 3 programs together

Could you explain further? Merriam-Webster defines dynamic as `marked by usually continuous and productive activity or change`, which could be interpreted to fit this project in a multitude of ways.

Your original suggestion, `dnotify` (`dnotify`, `dnotify-ctl`, and `dnotify-d`), seems good enough to me, though it highly resembles `xnotify`.

**Comment by wael444** [comment]
> I like these suggestions, but sn sounds too much like a coreutil and snotif sounds a little silly when pronounced.

`snot` :D

silly name but has the same vibe as `foot` 

> I don't think this program is very dynamic since it comes with 3 programs together

I don't know, i'm not good at explaining but i thought dynamic sort of meant one entire program, but considering this uses a client application and not a FIFO - like xnotify.
